[package]
id = hypnogram_viz

[id]
version = 0.2.6
name = hypnogram_viz

[ui]
is_visible = 1
label = Hypnogram
show_in_nav = 0

[launcher]
author = Tony Vincent
description = Stepped lane-timeline (hypnogram) custom visualization for Splunk Dashboard Studio. Source & docs: https://github.com/narwhaldc/hypnogram_viz
version = 0.2.6

[install]
is_configured = 0
build = <@- buildNumber @>
check_for_updates = 0

[manifest]
category = Custom
